printWidth: 90
tabWidth: 4
overrides:
    - files: "*.{json,yml,yaml}"
      options:
          endOfLine: "auto"
    - files: "**/lwc/**/*.html"
      options:
          parser: lwc
    - files: "**/lwc/**/*.js"
      options:
          trailingComma: "es5"
    - files: "**/aura/**/*.{cmp,page,component,xml}"
      options:
          parser: "html"
    - files: "**/aura/**/*.js"
      options:
          trailingComma: "none"
    - files: "**/classes/**/*.cls"
      options:
          plugins:
              - "./node_modules/prettier-plugin-apex"
          parser: apex
          apexInsertFinalNewline: true
    - files: "**/triggers/*.cls"
      options:
          plugins:
              - "./node_modules/prettier-plugin-apex"
          parser: apex
          apexInsertFinalNewline: true
    - files: "*.apex"
      options:
          plugins:
              - "./node_modules/prettier-plugin-apex"
          parser: apex
          apexAnonymous: true
          apexInsertFinalNewline: true

