<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>HEDA</application>
        <default>true</default>
        <visible>true</visible>
    </applicationVisibilities>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.Academic_Program</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.Administrative</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.Business_Organization</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.Educational_Institution</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Household Layout</layout>
        <recordType>Account.HH_Account</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.Sports_Organization</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-HEDA Organization Layout</layout>
        <recordType>Account.University_Department</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Contact-HEDA Contact Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Course_Enrollment__c-HEDA Course Enrollment Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Course_Enrollment__c-HEDA Course Enrollment Layout</layout>
        <recordType>Course_Enrollment__c.Default</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Course_Enrollment__c-HEDA Course Enrollment Layout</layout>
        <recordType>Course_Enrollment__c.Faculty</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Course_Enrollment__c-HEDA Course Enrollment Layout</layout>
        <recordType>Course_Enrollment__c.Student</recordType>
    </layoutAssignments>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.Academic_Program</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>true</default>
        <recordType>Account.Administrative</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.Business_Organization</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.Educational_Institution</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.HH_Account</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.Sports_Organization</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Account.University_Department</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Course_Enrollment__c.Default</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Course_Enrollment__c.Faculty</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>true</default>
        <recordType>Course_Enrollment__c.Student</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Idea.InternalIdeasIdeaRecordType</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <tabVisibilities>
        <tab>Address__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Affiliation__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Course_Enrollment__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Course_Offering__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Course__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>HEDA_Settings</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Program_Enrollment__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Relationship__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Term__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Trigger_Handler__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-Account</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-Contact</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>