eda_lex_locators = {
    "mailing_address": "//*[contains(@placeholder,'{}')]",
    "record": {
        "actions": "//div[contains(@class, 'actionsContainer')]/descendant::a[@title='{}']",
        "button": "//div[@class='actionsContainer']/button[@title='{}']",
        "datepicker": "//div[contains(@class,'uiDatePickerGrid')]/table[@class='calGrid']//span[text()='{}']",
        "edit_button": '//*[@title="{}"]',
        "list": "//div[contains(@class,'forcePageBlockItem')]//div//div//div//span//span[contains(text(), 'Primary Address Type')]/../../div/div/div/div/a[@class='select']",
        "related": {
            "new": "//div[@class='container']/descendant::div[contains(@class, 'slds-card__header')]/header/descendant::span[text()='{}']/ancestor::header/following-sibling::div/descendant::a[@title='New']",
            "title": '//div[contains(@class, "slds-card")]/header[.//span[@title="{}"]]',
        },
    },
    "eda_settings": {
        "tab": "//div[@id='tabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
        "edit": "//button[contains(@class, 'slds-button') and @type='button']/span[text()='Edit']/..",
        "checkbox_default": "//span[text()='{}']/../following-sibling::div/descendant::img",
        "checkbox": "//span[text()='{}']/../following-sibling::div/descendant::label[contains(@class,'slds-checkbox')]/span[contains(@class, 'slds-checkbox--faux')]",
        "save": "//div[contains(@class, 'slds-page-header')]/descendant::button[contains(@class, 'settings-save-bttn')]",
        "system_tab": "//a[contains(text(),'System')]",
        "affiliations_tab": "//a[contains(text(),'Affiliations')]",
        "affiliations_check": "//span[text()='Specify Role for Created Affiliations:']/../following-sibling::div/div/div/label/span/img[@class = 'copy-start-date checked' and @alt='True']",
        "affiliations_role_checkbox": "//input[@class='copy-start-date uiInput uiInputCheckbox uiInput--default uiInput--checkbox']/following-sibling::span",
        "affiliation_mappings_tab": "//a[contains(text(), 'Affiliation Mappings')]",
        "courses": "//a[contains(text(),'Courses')]",
        "duration": "//div[.//span[text()='Duration'] and contains(@class, 'slds-form-element') ]//select//option[@value='60']",
        "hh_naming_check": "//input[@class='automatic-hh-acc uiInput uiInputCheckbox uiInput--default uiInput--checkbox']/following-sibling::span",
        "hh_naming_role_checkbox": "//select[@class='admin-account-naming-input-select select uiInput uiInputSelect uiInput--default uiInput--select']//option[@value='{{!{{!FirstName}}}} {{!LastName}} Administrative Account']",
        "hh_adminfnamelname": "//input[contains(@class,'firstName')]",
        "course_connections_tab": "//a[contains(text(),'Course Connections')]",
        "cc_checkbox": "//input[contains(@class,'slds-checkbox')]/parent::label",
        "student_select": "//select[contains(@class,'student-course-connection-record-type-input-select')]",
        "faculty_select": "//select[contains(@class,'faculty-course-connection-record-type-input-select')]",
    },
    "tabs": {
        "accountsandcontacts" : "//a[contains(text(),'Accounts and Contacts')]",
    },
    "account_types": {
        "administrative": "//span[contains(text(),'Administrative')]/parent::*",
        "academic": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'Academic Program')]",
        "business": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'Business Organization')]",
        "educational": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'Educational Institution')]",
        "household": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'Household Account')]",
        "sports": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'Sports Organization')]",
        "university": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'University Department')]",
        "save": "//button[contains(@class, 'slds-button')]/span[text()='Save']/..",
        "edit": "//button[contains(@class, 'slds-button')]/span[text()='Edit']/..",
        "cancel": "//button[contains(@class, 'slds-button')]/span[text()='Cancel']/..",
    },
    "contact": {
        "new_button": "//a[@title='New']//div[@title='New']",
        "first_name": "//input[contains(@class,'firstName')]",
        "last_name":  "//input[contains(@class,'lastName')]",
        "save_button": "//button[@title='Save']",
        "program_enrollment_new_button": "//div[contains(@class, 'windowViewMode-normal')]//span[text()='Program Enrollments']/following-sibling::span[@title='(0)']/ancestor::header/following-sibling::div/descendant::a[@title='New']",
    },
    "program_plans": {
        "program_plan": "(//a[@title='Program Plans'])[2]/span/span",
        "new_button": "//a[@title='New']//div[@title='New']/..",
        "pp_name": "//div//div//div//div//div//div//div//label//span[contains(text(), 'Program Plan Name')]//../following-sibling::input",
        "save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
    },
    "plan_requirement": {
        "error": "//div[contains(@class, 'pageLevelErrors')]/descendant::li[text()='{}']",
        "parent_plan_req_name": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Parent Plan Requirement']/../following-sibling::div/descendant::span[text()='{}']",
        "plan_requirement_name": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Plan Requirement Name']/../following-sibling::input",
        "program_plan": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Program Plan']/../following-sibling::div/descendant::span[text()='{}']",
        "delete_field": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='{}']/../following-sibling::div/descendant::span[text()='{}']/following-sibling::a[@class='deleteAction']",
        "toast_message": "//lightning-icon[contains(@class, 'toastIcon') and contains(@class, 'slds-icon-utility-success')]",
    },
    "course_offering": {
        "search_courses": "//div/input[@title='Search Courses']",
        "new_button": "//a[@title='New']//div[@title='New']/..",
        "new_course_button": "//span[@class='itemLabel slds-truncate slds-show--inline-block slds-m-left--xx-small' and contains(text(), 'New Course')]",
        "save_button": "(//span[@class=' label bBody' and text()='Save']/ancestor::button[contains(@class, 'slds-button')])[3]",
        "next_save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
        "final_save_button": "(//span[@class=' label bBody' and text()='Save'])[3]/ancestor::button",
    },
    "term": {
        "new_term_button": "//span[@class='itemLabel slds-truncate slds-show--inline-block slds-m-left--xx-small' and contains(text(), 'New Term')]//..",
        "save_button": "(//span[@class=' label bBody' and contains(text(), 'Save')])[5]/..",
        "account": "//div//input[@title='Search Accounts']",
        "search_terms": "//input[@title='Search Terms']",
        "course_offering_id": "//span[contains(text(), 'Course Offering ID')]//../following-sibling::input",
    },
    "new_account": "//span[@title='New Account']",
    "new_account_next_button": "//button[contains(@class, 'slds-button')]//span[@class=' label bBody' and text()='Next']",
    "new_account_name": "//input[@class='input uiInput uiInputText uiInput--default uiInput--input']",
    "new_account_save_button": "//div[contains(@class, 'slds-modal__footer')]/descendant::button[@title='Save']",
    "academic_program": "//span[contains(text(), 'Academic Program')]",
    "new_program_enrollment_save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
    "affiliated_accounts_count": "//span[text()='Affiliated Accounts']/following-sibling::span[contains(@title, '(1)')]",
    "program_enrollments_count": "//span[text()='Program Enrollments']/following-sibling::span[contains(@title, '(1)')]",
    "programenrollment_account": "//div[@class='autocompleteWrapper slds-grow']//input[@class=' default input uiInput uiInputTextForAutocomplete uiInput--default uiInput--input uiInput uiAutocomplete uiInput--default uiInput--lookup']",
    "list_of_departments": "//button[contains(@class, 'slds-button slds-button--neutral')]//span[@class=' label bBody' and text()='Next']",
    "tab": "//div[@class='uiTabBar']/ul[@class='tabs__nav']/li[contains(@class,'uiTabItem')]/a[@class='tabHeader']/span[contains(text(), '{}')]",
    "account_list": '//tbody/tr/th[.//span[contains(@class, "slds-grid")]]/descendant::a[text()="{}"]',
    "header_field_value": '//li[contains(@class,"slds-page-header__detail")]//div//span[contains(@title,"{}")]/following-sibling::div/div/div/a[contains(text(), "{}")]',
    "modal": {
        "checkbox": '//div[contains(@class,"uiInputCheckbox")]/label/span[text()="{}"]/../following-sibling::input[@type="checkbox"]',
        "save": "//div[contains(@class, 'footer') or contains(@class, 'Footer')]/descendant::button[@title='Save']",
    },
    "toast_message": "//div[contains(@class, 'slds-notify--toast')]/descendant::h2[contains(@class, 'slds-text-heading') and text()='{}']",
    "toast_close": "//div[contains(@class, 'slds-theme--success')]/button[contains(@class, 'slds-notify__close')]",
    "input_placeholder": "//input[contains(@placeholder,'{}')]",
}