""" Locators for Winetr '21 """

eda_lex_locators = {
    "app_tile": "//one-app-launcher-modal//one-app-launcher-app-tile//a[.='{}']",
    "frame": "//iframe[contains(@id, '{}') or contains(@title, '{}') or contains(@name, '{}')]",
    "input_placeholder": "//input[contains(@placeholder,'{}')]",
    "panel_tab_lookup": "//a/span[text()='{}']",
    "toast_message": "//div[@id='successToast']/descendant::h2[text()='{}']",
    "success_message": "//div[@id='successToast']/descendant::h2[text()='{}']",
    "toast_close": "//div[@id='successToast']/descendant::button[contains(@class, 'slds-notify__close')]",
    "close_tab": "//*[@data-key='close']/ancestor::button[contains(@class, 'slds-button slds-button_icon-x-small')]",
    "mailing_address": "//*[contains(@placeholder,'{}')]",
    "record": {
        "actions": "//div[contains(@class, 'actionsContainer')]/descendant::a[@title='{}']",
        "button": "//div[@class='actionsContainer']/button[@title='{}']",
        "datepicker": "//div[contains(@class,'uiDatePickerGrid')]/table[@class='calGrid']//span[text()='{}']",
        "edit_button": '//*[@title="{}"]',
        "list": "//div[contains(@class,'forcePageBlockItem')]//div//div//div//span//span[contains(text(), 'Primary Address Type')]/../../div/div/div/div/a[@class='select']",
        "related": {
            "new": "//div[@class='container']/descendant::div[contains(@class, 'slds-card__header')]/header/descendant::span[text()='{}']/ancestor::header/following-sibling::div/descendant::a[@title='New']",
            "title": '//div[contains(@class, "slds-grid")]/header//a[./span[text()="{}"]]',
        },
    },
    "tabs": {
        "tab": "//div[@class='uiTabBar']/ul[@class='tabs__nav']/li[contains(@class,'uiTabItem')]/a[@class='tabHeader']/span[contains(text(), '{}')]",
        "spl-tab": "//div[@class='slds-tabs_default']//ul[@class='slds-tabs_default__nav']/li[contains(@class,'slds-tabs_default__item')]/a[text()= '{}']",
    },
    "eda_settings": {
        "action": "//div[@role='banner']/descendant::button[contains(@class, 'settings-{}-bttn')]",
        "edit": "//div[@class='slds-page-header' and @role='banner']/descendant::span[text()='Edit']/parent::button",
        "tab": "//div[@id='tabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
        "checkbox_default": "//span[text()='{}']/../following-sibling::div/descendant::img",
        "checkbox": "//span[text()='{}']/../following-sibling::div/descendant::label[contains(@class,'slds-checkbox')]/span[contains(@class, 'slds-checkbox--faux')]",
        "save": "//div[contains(@class, 'slds-page-header')]/descendant::button[contains(@class, 'settings-save-bttn')]",
        "system_tab": "//a[contains(text(),'System')]",
        "affiliations_tab": "//a[contains(text(),'Affiliations')]",
        "affiliations_check": "//span[text()='Specify Role for Created Affiliations']/../following-sibling::div/div/div/label/span/img[@class = 'copy-start-date checked' and @alt='True']",

        "auto_enroll_business_organization": "//div/span[text()='Primary Business Organization']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",
        "auto_enroll_educational_institution": "//div/span[text()='Primary Educational Institution']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",
        "auto_enroll_household_account": "//div/span[text()='Primary Household']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",
        "auto_enroll_sports_organization": "//div/span[text()='Primary Sports Organization']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",
        "auto_enroll_university_department": "//div/span[text()='Primary Department']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",

        "primary_affl_unchecked": "//div/span[text()='{}']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "checkbox_ap_affl": "(//label[@class='slds-checkbox']/input[@class='mapping-auto-enroll uiInput uiInputCheckbox uiInput--default uiInput--checkbox'])[1]/following-sibling::span[@class='slds-checkbox--faux']",
        "primary_affl_edit": "(//label/span[text()='Primary Affl Field: {}']/../../../following-sibling::div/div/div/label)[1]/input/following-sibling::span[@class='slds-checkbox--faux']",

        "affiliations_role_checkbox": "//input[@class='copy-start-date uiInput uiInputCheckbox uiInput--default uiInput--checkbox']/following-sibling::span",
        "affiliation_mappings_tab": "//a[contains(text(), 'Affiliation Mappings')]",
        "courses": "//a[contains(text(),'Courses')]",
        "duration": "//div[.//span[text()='Duration'] and contains(@class, 'slds-form-element') ]//select//option[@value='60']",
        "hh_naming_check": "//input[@class='automatic-hh-acc uiInput uiInputCheckbox uiInput--default uiInput--checkbox']/following-sibling::span",
        "hh_naming_role_checkbox": "//select[@class='admin-account-naming-input-select select uiInput uiInputSelect uiInput--default uiInput--select']//option[@value='{{!{{!FirstName}}}} {{!LastName}} Administrative Account']",
        "hh_adminfnamelname": "//input[contains(@class,'firstName')]",
        "course_connections_tab": "//a[contains(text(),'Course Connections')]",
        "cc_checkbox": "//input[contains(@class,'slds-checkbox')]/parent::label",
        "student_select": "//select[contains(@class,'student-course-connection-record-type-input-select')]",
        "faculty_select": "//select[contains(@class,'faculty-course-connection-record-type-input-select')]",
        "status_student_affl": "//select[contains(@class,'affiliation-role-picklist-input-select')]",
        "status_spec_affl_not_deleted_former": "//select[contains(@class,'affiliation-status-delete-picklist-input-select')]",
        "status_current_picklist_affl": "//select[contains(@class,'affiliation-status-picklist-input-select')]",
        "default_account_model": "//span[text()='Default Account Model']",
        "store_errors": "//span[text()='Store Errors']",
        "send_error_notifications": "//span[text()='Send Error Notifications']",
        "error_notification_recipients": "//span[text()='Error Notification Recipients']",
        "disable_error_handling": "//span[text()='Disable Error Handling']",
        "automatic_household_naming": "//span[text()='Automatic Household Naming']",
        "adminstrative_account_name_format": "//span[text()='Administrative Account Name Format']",
        "household_account_name_format": "//span[text()='Household Account Name Format']",
        "batch_processing": "(//td/following-sibling::td[text()='Batch Apex']/following-sibling::td[text()='Processing'])[1]",
        "just_batch": "(//td/following-sibling::td[text()='Batch Apex'])[1]",
        "batch_watch": "(//td/following-sibling::td[text()='Batch Apex']/following-sibling::td)[1]",
        "wait_frame": "//iframe[contains(@title,'Apex Jobs ~ Salesforce - Developer Edition')]",
        "wait_loc_text": "(//td/following-sibling::td[text()='Batch Apex']/following-sibling::td)[1]",
        "new_account": "//span[@title='New Account']",
        "affiliated_accounts": "//span[@title='Affiliated Accounts']",
        "affiliation_match": "//span/a[@title='Robot Academic Program Account']",
        "edit_button": "//div[@class='slds-button-group']//span[contains(text(), 'Edit')]",
        "save_button": "//div[@class='slds-button-group']//span[contains(text(), 'Save')]",
        "administrative_account": "//div/a[text()='{} Administrative Account']",
        "contact_edit": "//a[@title='Edit']",
        "en_re_type_validation": "(//div/span[text()='Enable Record Type Validation']/following::div)[1]/div/div/label/span[@class='slds-checkbox--faux']",
        "ert_validation": "//span/img[@class='affl-record-type-enforced checked' and @alt='True']",
        "un_ert_validation": "//span/img[@class='affl-record-type-enforced unchecked' and @alt='False']",
        "delete_rec_affl": "//span/img[@class='delete-prog-enroll checked' and @alt='True']",
        "un_delete_rec_affl": "//span/img[@class='delete-prog-enroll unchecked' and @alt='False']",
        "del_rel_affl": "(//div/span[text()='Delete Related Affiliation When Deleting Program Enrollment']/following::div)[1]/div/div/label/span[@class='slds-checkbox--faux']",
        "specify_role_for_c_affl": "(//div/div/span[text()='Specify Role for Created Affiliations']/following::span)[1]/img[@class='copy-start-date checked' and @alt='True']",
        "un_specify_role_for_c_affl": "(//div/div/span[text()='Specify Role for Created Affiliations']/following::span)[1]/img[@class='copy-start-date unchecked' and @alt='False']",
        "specify_r_checkbox": "(//div/span[text()='Specify Role for Created Affiliations']/following::div)[1]/div/div/label/span[@class='slds-checkbox--faux']",
        "copy_affl_end_date": "//span/img[@class='copy-end-date checked' and @alt='True']",
        "un_copy_affl_end_date": "//span/img[@class='copy-end-date unchecked' and @alt='False']",
        "copy_affliation_end_checkbox": "(//div/span[text()='Copy Affiliation End Date from Program Enrollment']/following::div)[1]/div/div/label/span[@class='slds-checkbox--faux']",
        "copy_affl_start_date": "(//div/div/span[text()='Copy Affiliation Start Date from Program Enrollment']/following::span)[1]/img[@class='copy-start-date checked' and @alt='True']",
        "un_copy_affl_start_date": "(//div/div/span[text()='Copy Affiliation Start Date from Program Enrollment']/following::span)[1]/img[@class='copy-start-date unchecked' and @alt='False']",
        "copy_affliation_start_checkbox": "(//div/span[text()='Copy Affiliation Start Date from Program Enrollment']/following::div)[1]/div/div/label/span[@class='slds-checkbox--faux']",
        "settings_tab": "(//li[@class='slds-tabs__item slds-text-heading--label slds-active' and @role='tab' and @title='Settings'])[1]/a[contains(text(),'Settings')]",
        "affl_mappings_tab": "//a[contains(text(),'Affiliation Mappings')]",
        "default_checkbox": "//div[text()='{}']/following-sibling::div/descendant::img",
        "enable_checkbox": "(//div[text()='{}']/following-sibling::div/descendant::span)[1]",
        "dropdown_field": "//div[text()='{}']/following-sibling::div/select",
        "action_button": "//button[text()='{}']",
        "update_checkbox": "//span[text()='{}']/../following-sibling::div[1]/descendant::span[contains(@class, 'checkbox')]",
        "add_setting_button": "//span[text()='{}']/../following-sibling::button/span[text()='{}']",
    },
     "eda_settings_cc": {
        "default_cc_checkbox": "//div[text()='Enable Course Connections']/following-sibling::div/descendant::img",
        "dropdown_values": "//div[text()='{}']/following-sibling::div/select/option[text()='{}']",
        "dropdown_values_count": "//div[text()='{}']/following-sibling::div/select/option",
        "enable_cc_checkbox": "//div[text()='Enable Course Connections']/following-sibling::div[1]/descendant::span",
        "enable_cc_warning_enabled": "//div[contains(@class, 'slds-notify') and @role='alert']/descendant::*[@data-key='warning']/../../following-sibling::span[text()='You must enable Course Connections before editing record types.']",
        "enable_cc_warning_disabled": "//span[contains(@class, 'slds-hide')]/descendant::div[contains(@class, 'slds-notify') and @role='alert']/descendant::*[@data-key='warning']/../../following-sibling::span[text()='You must enable Course Connections before editing record types.']",
        "updated_dropdown_value": "//div[text()='{}']/following-sibling::div/descendant::span[text()='{}']",
        "settings_tab": "//div[contains(@class, 'CourseConnections')]/descendant::a[text()='Settings']",
        "backfill_warning_enabled": "//div[contains(@class, 'slds-notify--alert')]/descendant::span[text()='You must enable Course Connections before running the Course Connections Backfill.']",
        "backfill_warning_disabled": "//span[contains(@class, 'slds-hide')]/descendant::span[text()='You must enable Course Connections before running the Course Connections Backfill.']",
        "cc_sub_tabs": "//div[contains(@class, 'CourseConnections')]/descendant::a[text()='{}']",
        "backfill_button_status": "//span[text()='{}']/parent::button",
        "backfill_checkbox_status": "//input[contains(@class, 'backfill')]/following-sibling::span[contains(@class, 'checkbox')]",
    },
    "eda_settings_program_plans": {
        "checkbox_read": "(//span[text()='{}']/../following-sibling::div/descendant::img)[1]",
        "checkbox_edit": "(//span[text()='{}']/../following-sibling::div/descendant::span)[1]",
        "updated_checkbox_edit": "//span[text()='{}']/../following-sibling::div[1]/descendant::span[contains(@class, 'checkbox')]",
    },
    "eda_settings_courses": {
        "text_message": "//span[text()='{}']",
    },
    "eda_settings_relationships": {
        "dropdown_read": "//span[text()='{}']/../following-sibling::div[1]/descendant::span",
        "dropdown_value": "//span[text()='{}']/../following-sibling::div/descendant::select/option[text()='{}']",
        "new_reciprocal_setting": "//div[contains(@class, 'newrecsetting')]/descendant::span[text()='{}']/following::input[1]",
        "sub_tab": "//div[@id='relTabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
        "active_checkbox": "//span[text()='{}']/following::input[contains(@class, 'new-rec-sett')]/../span[contains(@class, 'checkbox')]",
        "add_setting_button": "//div[contains(@class, 'newrecsetting')]/descendant::span[text()='{}']",
        "settings_count": "//span[contains(@class, 'Checkbox')]/img[contains(@class, 'rec-settg')]",
        "new_settings": "(//div[@class='newrecsetting']/preceding-sibling::div[1]/div)[last()-{}]/span[contains(@class, 'rec-settg-{}') and text()='{}']",
        "new_setting_edit": "(//div[@class='newrecsetting']/preceding-sibling::div[1]/div)[last()-{}]/descendant::input[contains(@class, 'rec-settg-{}')]/../label/span[text()='{}: {}']",
        "new_setting_checkbox": "(//div[@class='newrecsetting']/preceding-sibling::div[1]/div)[last()-1]/descendant::img[contains(@class, 'rec-settg-{}')]",
        "new_setting_checkbox_edit": "(//div[@class='newrecsetting']/preceding-sibling::div[1]/div)[last()-1]/descendant::input[contains(@class, 'rec-settg-{}')]/../span[contains(@class, 'checkbox')]",
        "delete_setting_icon": "//span[text()='{}: {}']/following::lightning-icon[1][contains(@class, 'delete')]",
        "removed_setting": "//span[contains(@class, 'rec-settg-{}') and text()='{}']",
        "updtate_setting_name": "//span[text()='Name: {}']/../following-sibling::input[contains(@class, 'rec-settg-{}')]",
        "update_setting_name_cleared": "//span[text()='Name: ']/../following-sibling::input[contains(@class, 'rec-settg-name')]",
        "update_setting_rest": "(//span[text()='Name: {}']/following::input[contains(@class, 'rec-settg-{}')])[1]",
        "updated_setting": "//span[contains(@class, 'rec-settg-name') and text()='{}']/following::div/span[contains(@class, 'rec-settg-{}') and text()='{}']",
        "test_locator": "(//div[@class='newrecsetting']/preceding-sibling::div[1]/div)[last()-2]/descendant::input[contains(@class, 'rec-settg-neutral')]",
    },
    "eda_settings_system": {
        "default_checkbox": "//span[text()='{}']/../following-sibling::div[1]/descendant::img",
        "default_dropdown_value": "//span[text()='{}']/../following-sibling::div[1]/descendant::span[text()='{}']",
        "admin_success_toast": "//div[@id='adminSuccessToast']/descendant::h2",
        "hh_success_toast": "//div[@id='hhSuccessToast']/descendant::h2",
        "other_accname_format": "//span[text()='{}']/../preceding-sibling::div[1]/descendant::input",
        "other_dropdown_value": "//span[text()='{}']/../preceding-sibling::div[1]/descendant::span[text()='{}']",
        "recipient_type_value": "//span[text()='{}']/../following-sibling::div/descendant::select/option[@value='{}']",
        "recipient_name": "//label[text()='{}']/../div/descendant::input",
        "recipient_lookup": "//div[contains(@class, 'lookup') and text()='{}']",
    },
    "account_types": {
        "administrative": "//span[contains(text(),'Administrative')]/parent::*",
        "household": "//span[text()='Household Account']/preceding-sibling::span",
        "account_checkbox": "//div[contains(@class,'slds-form-element__control')]//span[contains(text(),'{}')]",
        "save": "//button[contains(@class, 'slds-button')]/span[text()='Save']/..",
        "edit": "//button[contains(@class, 'slds-button')]/span[text()='Edit']/..",
        "cancel": "//button[contains(@class, 'slds-button')]/span[text()='Cancel']/..",
    },
    "contact": {
        "new_button": "//a[@title='New']//div[@title='New']",
        "first_name": "//input[contains(@class,'firstName')]",
        "last_name":  "//input[contains(@class,'lastName')]",
        "save_button": "//button[@title='Save']",
        "program_enrollment_new_button": "//div[contains(@class, 'windowViewMode-normal')]//span[text()='Program Enrollments']/following-sibling::span[@title='(0)']/ancestor::header/following-sibling::div/descendant::a[@title='New']",
    },
    "program_plans": {
        "program_plan": "(//a[@title='Program Plans'])[2]/span/span",
        "new_button": "//a[@title='New']//div[@title='New']/..",
        "pp_name": "//div//div//div//div//div//div//div//label//span[contains(text(), 'Program Plan Name')]//../following-sibling::input",
        "save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
    },
    "plan_requirement": {
        "error": "//div[contains(@class, 'pageLevelErrors')]/descendant::li[text()='{}']",
        "parent_plan_req_name": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Parent Plan Requirement']/../following-sibling::div/descendant::span[text()='{}']",
        "plan_requirement_name": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Plan Requirement Name']/../following-sibling::input",
        "program_plan_name": "//td/a[@title='{}']",
        "program_plan": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='Program Plan']/../following-sibling::div/descendant::span[text()='{}']",
        "delete_field": "//div[contains(@class, 'slds-modal__container')]/descendant::span[text()='{}']/../following-sibling::div/descendant::span[text()='{}']/following-sibling::a[@class='deleteAction']",
        "toast_message": "//lightning-icon[contains(@class, 'toastIcon') and contains(@class, 'slds-icon-utility-success')]",
    },
    "course_offering": {
        "search_courses": "//div/input[@title='Search Courses']",
        "new_button": "//a[@title='New']//div[@title='New']/..",
        "new_course_button": "//span[@class='itemLabel slds-truncate slds-show--inline-block slds-m-left--xx-small' and contains(text(), 'New Course')]",
        "save_button": "(//span[@class=' label bBody' and text()='Save']/ancestor::button[contains(@class, 'slds-button')])[3]",
        "next_save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
        "final_save_button": "(//span[@class=' label bBody' and text()='Save'])[3]/ancestor::button",
    },
    "term": {
        "new_term_button": "//span[@class='itemLabel slds-truncate slds-show--inline-block slds-m-left--xx-small' and contains(text(), 'New Term')]//..",
        "save_button": "(//span[@class=' label bBody' and contains(text(), 'Save')])[5]/..",
        "account": "//div//input[@title='Search Accounts']",
        "search_terms": "//input[@title='Search Terms']",
        "course_offering_id": "//span[contains(text(), 'Course Offering ID')]//../following-sibling::input",
    },
    "custom_settings": {
        "hierarchy_settings": "//a[text()='Hierarchy Settings']",
        "manage": "//span/input[@value='Manage']",
        "no_records": "//table//td[text()='No records to display.']",
        "custom_settings_frame":      "//iframe[contains(@title,'Custom Settings ~ Salesforce')]",
        "custom_settings_definition": "//iframe[contains(@title,'Custom Setting Definition ~ Salesforce')]",
        "custom_settings_h_settings": "//iframe[contains(@title,'Custom Setting Hierarchy Settings ~ Salesforce')]",
    },
    "new_account": "//span[@title='New Account']",
    "new_account_next_button": "//button[contains(@class, 'slds-button')]//span[@class=' label bBody' and text()='Next']",
    "new_account_name": "//label/span[text()='Account Name']/following-sibling::span/following::input[1]",
    "new_account_save_button": "//div[contains(@class, 'slds-modal__footer')]/descendant::button[@title='Save']",
    "academic_program": "//span[contains(text(), 'Academic Program')]",
    "new_program_enrollment_save_button": "//div[contains(@class, 'inlineFooter')]/descendant::button[@title='Save']",
    "affiliated_accounts_count": "//span[text()='Affiliated Accounts']/following-sibling::span[contains(@title, '(1)')]",
    "custom_settings_title": "//a/mark[text()='{}']",
    "program_enrollments_count": "//span[text()='Program Enrollments']/following-sibling::span[contains(@title, '(1)')]",
    "programenrollment_account": "//div[@class='autocompleteWrapper slds-grow']//input[@class=' default input uiInput uiInputTextForAutocomplete uiInput--default uiInput--input uiInput uiAutocomplete uiInput--default uiInput--lookup']",
    "list_of_departments": "//button[contains(@class, 'slds-button slds-button--neutral')]//span[@class=' label bBody' and text()='Next']",
    "tab": "//div[@class='uiTabBar']/ul[@class='tabs__nav']/li[contains(@class,'uiTabItem')]/a[@class='tabHeader']/span[contains(text(), '{}')]",
    "account_list": '//tbody/tr/th[.//span[contains(@class, "slds-grid")]]/descendant::a[text()="{}"]',
    "header_field_value": '//*[contains(@class, "slds-page-header__detail")][.//*[@title="{}"]]//*[text()="{}"]',
    "modal": {
        "checkbox": '//div[contains(@class,"uiInputCheckbox")]/label/span[text()="{}"]/../following-sibling::input[@type="checkbox"]',
        "save": "//div[contains(@class, 'footer') or contains(@class, 'Footer')]/descendant::button[@title='Save']",
    },
    "accounts_contacts_settings_locators": {
        "copy_from": "//select[@class='contact-preferred-phone-picklist-input-select select uiInput uiInputSelect uiInput--default uiInput--select']",
        "disable_checked": "(//span[text()='Disable Preferred Phone enforcement']/following::div/div/div/label/input/following-sibling::span)[1]",
        "disable_preferred_phone": "//div/span[text()='Disable Preferred Phone enforcement']/following::div[1]/div/div/label/span/img[@alt='False']",
        "enhanced_preferred_clear": "//div/span[text()='Enable Enhanced Preferred Phone Functionality']/following::div[1]/div/div/label/span/img[@alt='False']",
        "enhanced_preferred_clear_faux": "//span[text()='Enable Enhanced Preferred Phone Functionality']/following::div[1]/div/div/label/input/following::span[1]",
        "enhanced_preferred_set": "//span[text()='Enable Enhanced Preferred Phone Functionality']/following::div[1]/div/div/label/span/img[@alt='True']",
        "enhanced_preferred_set_faux": "//span[text()='Enable Enhanced Preferred Phone Functionality']/following::div[1]/div/div/label/input/following::span[1]",
        "preferred_phone_active": "//div/span[text()='Disable Preferred Phone enforcement']/following::div[1]/div/div/label/span/img[@alt='True']",
    },
    "relationships_settings_locators": {
        "sub_tab": "//div[@id='relTabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
    },
    "contacts_locators": {
        "contact_save": "//div[contains(@class,'modal-footer')]//button[@title='Save']//span[text()='Save']",
        "header": "//a[@title='Contacts']//span",
        "select_contact": "//a[@title='{} {}']",
        "preferred_phone": "//span//span[contains(text(),'Preferred Phone')]",
        "preferred_phone_home_dropdown": "//span//span[contains(text(),'Preferred Phone')]/following::span/following::a",
        "preferred_tab": "//div[@class='select-options']/descendant::a[@title='Home Phone']",
        "phone_verify_has_number": "(//div//span[text()='Phone']/../following-sibling::div//span[not( text()='123-123-1234')])[1]",
        "preferred_error_message": "//li[contains(text(), 'The phone selected for Preferred Phone can')]",
        "which_preferred_error_message": "//li[contains(text(), 'Tell us which Phone is preferred.')]",
        "field_for_work_phone": "//div//label//span[contains(text(),'Work Phone')]/../following-sibling::input",
        "which_footer_cancel": "//div[contains(@class,'footer')]/button[@title='Cancel']//span[text()='Cancel']",
        "footer_save": "//div[contains(@class,'modal-footer')]//span[text()='Save']",
        "accounts_contacts": "//a[contains(text(),'Accounts and Contacts')]",
        "details_tab": "//div[contains(@class,'normal')]//span[@class='title' and text()='Details']",
        "phone_home": "//span[text()='Home Phone']/../following-sibling::input",
        "run_cleanup": "//button[text()='Run Cleanup']",
        "phone_verify": "//div//span[text()='Home Phone']/../following-sibling::div//span//span[text()='123-123-1234']",
        "home_phone_verify": "//span[text()='Home Phone']/../following::div//span//span[text()='123-123-1234']",
        "successful_run": "//span[text()='The process was queued successfully. An email will be sent at the completion of the job.']",
        "apex_jobs": "//a/mark[text()='{}']",
        "primary_business_organization": "(//span[text()='Primary Business Organization']/following::div/div/div/div/input[@title='Search Accounts'])[1]",
        "button_save_affiliation": "//button[@title='Save']//span[text()='Save']",
        "delete_icon": "//span[@class='deleteIcon']",
    },
    "affiliations_locators": {
        "header": "//a[@title='EDA Settings']//span",
        "tab": "//div[@id='tabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
        "edit": "//button[contains(@class, 'slds-button') and @type='button']/span[text()='Edit']/..",
        "checkbox": "//span[text()='{}']/../following-sibling::div/descendant::label[contains(@class,'slds-checkbox')]/span[contains(@class, 'slds-checkbox--faux')]",
        "save": "//div[contains(@class, 'slds-page-header')]/descendant::button[contains(@class, 'settings-save-bttn')]",
        "sub_tab": "//div[@id='afflTabs']/descendant::li[contains(@class, 'slds-text-heading--label')]/a[text()='{}']",
        "edit_button": "//div[@class='slds-button-group']//span[contains(text(), 'Edit')]",
        "save_button": "//div[@class='slds-button-group']//span[contains(text(), 'Save')]",
        "un_ert_validation": "//span/img[@class='affl-record-type-enforced unchecked' and @alt='False']",
        "un_delete_rec_affl": "//span/img[@class='delete-prog-enroll unchecked' and @alt='False']",
        "specify_role_for_c_affl": "(//div/div/span[text()='Specify Role for Created Affiliations']/following::span)[1]/img[@class='copy-start-date checked' and @alt='True']",
        "copy_affl_end_date": "//span/img[@class='copy-end-date checked' and @alt='True']",
        "copy_affl_start_date": "(//div/div/span[text()='Copy Affiliation Start Date from Program Enrollment']/following::span)[1]/img[@class='copy-start-date checked' and @alt='True']",
        "affiliations_former": "//div/div/following::div/span[text()='Former']",
        "affiliations_student": "(//div/div/span[@class='uiOutputText' and text()='Role Specified for Created Affiliations']/following::div[@class='slds-col slds-size--1-of-2'])[1]/span[text()='Student']",
        "affiliations_current": "//div/div/following::div[@class='slds-col slds-size--1-of-2']/span[text()='Current']",

        "account_record_type_academic_program": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='Academic Program']",
        "contact_primary_affl_field_primary_academic_program": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Academic Program']",
        "auto_enroll_academic_program": "//div/span[text()='Primary Academic Program']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll checked' and @alt='True']",
        "auto_enrollment_edit_mode_status_academic_program": "(//span[text()='Primary Affl Field: Primary Academic Program']/../../../following-sibling::div/following-sibling::div/div/label/span[text()='Status: Current']/following::input)[1]",
        "ae_em_status_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "auto_enrollment_edit_mode_role_academic_program": "(//span[text()='Primary Affl Field: Primary Academic Program']/../../../following-sibling::div/following-sibling::div/div/label/span[text()='Role: Student']/following::input)[1]",
        "ae_em_role_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",
        "auto_enrollment_read_mode_status_academic_program": "(//div/span[text()='Primary Academic Program']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='Current']",
        "auto_enrollment_read_mode_role_academic_program": "(//div/span[text()='Primary Academic Program']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='Student']",

        "account_record_type_business_organization": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='Business Organization']",
        "contact_primary_affl_field_primary_business_organization": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Business Organization']",
        "auto_enroll_business_organization": "//div/span[text()='Primary Business Organization']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "ae_em_bo_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-acc-rec-type input']",
        "auto_enrollment_edit_mode_role_business_organization": "(//span[text()='Primary Affl Field: Primary Business Organization']/../../../following-sibling::div/following-sibling::div/following-sibling::div//span[text()='Role: ']/following::input)[1]",
        "ae_em_pbo_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-affl-field input']",
        "auto_enrollment_read_mode_status_business_organization": "(//div/span[text()='Primary Business Organization']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='']",
        "ae_enroll_bo_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "auto_enrollment_read_mode_role_business_organization": "(//div/span[text()='Primary Business Organization']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='']",
        "ae_enroll_bo_status_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",

        "account_record_type_educational_institution": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='Educational Institution']",
        "contact_primary_affl_field_primary_educational_institution": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Educational Institution']",
        "auto_enroll_educational_institution": "//div/span[text()='Primary Educational Institution']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "auto_enrollment_read_mode_status_educational_institution": "(//div/span[text()='Primary Educational Institution']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='']",
        "auto_enrollment_read_mode_role_educational_institution": "(//div/span[text()='Primary Educational Institution']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='']",
        "ei_art_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-acc-rec-type input']",
        "ei_cpaf_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-affl-field input']",
        "ei_aes_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "ed_aer_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",

        "account_record_type_household_account": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='Household Account']",
        "contact_primary_affl_field_primary_household": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Household']",
        "auto_enroll_household_account": "//div/span[text()='Primary Household']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "auto_enrollment_read_mode_status_household_account": "(//div/span[text()='Primary Household']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='']",
        "auto_enrollment_read_mode_role_household_account": "(//div/span[text()='Primary Household']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='']",
        "ha_art_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-acc-rec-type input']",
        "ha_cpaf_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-affl-field input']",
        "ha_aes_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "ha_aer_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",

        "account_record_type_sports_organization": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='Sports Organization']",
        "contact_primary_affl_field_primary_sports_organization": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Sports Organization']",
        "auto_enroll_sports_organization": "//div/span[text()='Primary Sports Organization']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "auto_enrollment_read_mode_status_sports_organization": "(//div/span[text()='Primary Sports Organization']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='']",
        "auto_enrollment_read_mode_role_sports_organization": "(//div/span[text()='Primary Sports Organization']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='']",
        "so_art_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-acc-rec-type input']",
        "pso_cpaf_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-affl-field input']",
        "so_aes_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "so_aer_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",

        "account_record_type_university_department": "//span[@class='mapping-acc-rec-type uiOutputText' and text()='University Department']",
        "contact_primary_affl_field_primary_department": "//span[@class='mapping-affl-field uiOutputText' and text()='Primary Department']",
        "auto_enroll_university_department": "//div/span[text()='Primary Department']/../following-sibling::div[1]//span/img[@class='mapping-auto-enroll unchecked' and @alt='False']",
        "auto_enrollment_read_mode_status_university_department": "(//div/span[text()='Primary Department']/../following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-status uiOutputText' and text()='']",
        "auto_enrollment_read_mode_role_university_department": "(//div/span[text()='Primary Department']/../following-sibling::div/following-sibling::div/following-sibling::div)[1]/span[@class='mapping-enroll-role uiOutputText' and text()='']",
        "ud_art_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-acc-rec-type input']",
        "ud_cpaf_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-affl-field input']",
        "ud_aes_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-status input']",
        "ud_aer_em_empty": "(//div[@class='slds-tabs__content slds-show']/div[@class='slds-grid slds-wrap']/div/following::div/label/input/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div/following::div)[1]//label/following-sibling::input[@class='mapping-enroll-role input']",

        "account_record_type_input": "//label/span[text()='Account Record Type']/../following-sibling::input",
        "primary_affl_field_input": "//label/span[text()='Primary Affl Field']/../following-sibling::input",
        "auto_enrollment": "(//label/span[text()='Auto-Enrollment']/following::br/following::div/label/input/following-sibling::span)[1][@class='slds-checkbox--faux']",
        "status_mapping_field_input": "//label/span[text()='Status']/../following-sibling::input",
        "role_mapping_field_input": "//label/span[text()='Role']/../following-sibling::input",

        "acc_record_type": "//label/span[text()='Acc Record Type: {}']/following::input[1][@class='mapping-acc-rec-type input' and @type='text']",
        "contact_primary_affl_field": "//label/span[text()='Primary Affl Field: {}']/following::input[1][@class='mapping-affl-field input' and @type='text']",

        "art_ap_input_affl_empty": "(//label/span[text()='Acc Record Type: ']/following::input[1][@class='mapping-acc-rec-type input' and @type='text'])[1]",
        "paf_pap_input_affl_empty": "(//label/span[text()='Primary Affl Field: ']/following::input[1][@class='mapping-affl-field input' and @type='text'])[1]",
    }
}
